import csgo from "@/assets/banner/csgo.jpg";
import fortnite from "@/assets/banner/fortnite-og-social-1920x1080-a5adda66fab9.jpg";
import pubg from "@/assets/banner/pubg-battlegrounds-9i69f.jpg";
import { PrimalChampionshipCardProps } from "../../types/types";

export const primalChampionship: PrimalChampionshipCardProps[] = [
  {
    title: "Global Domination Cup",
    image: fortnite,
    prize: {
      totalPrize: 1000,
      firstPrize: 100,
      secondPrize: 23,
      thirdPrize: 34,
    },
    description: "Wining prize",
    battleground: "Valhalla Grounds",
    teamSize: "4v4",
    maxTeams: 20,
    enrolled: 12,
    startingTime: "2025-01-15T14:00:00Z",
    thumbnailUrl: fortnite,
    subtitle:
      "Battle in Fortnite without the build mechanic for a true test of skill!",
    date: "2025-03-10T12:00:00.000Z",
    entryFee: 200,
    regions: "Asia",
    skillLevel: "Advanced",
    game: "fortnite",
    platform: "pc",
    enrolledTeams: 18,
    enrollmentStatus: false,
    registrationStatus: true,
  },
  {
    title: "Champion's League",
    image: csgo,
    prize: {
      totalPrize: 1000,
      firstPrize: 100,
      secondPrize: 23,
      thirdPrize: 34,
    },
    description: "First place prize",
    battleground: "Stadium Arena",
    teamSize: "5v5",
    maxTeams: 16,
    enrolled: 8,
    startingTime: "2025-02-20T10:00:00Z",
    thumbnailUrl: csgo,
    subtitle:
      "Prove your skills in this intense CS:GO tournament, where strategy and aim reign supreme.",
    date: "2025-04-05T09:00:00.000Z",
    entryFee: 200,
    regions: "Europe",
    skillLevel: "Intermediate",
    game: "csgo",
    platform: "pc",
    enrolledTeams: 10,
    enrollmentStatus: true,
    registrationStatus: false,
  },
  {
    title: "Ultimate Battle Royale",
    image: pubg,
    prize: {
      totalPrize: 1000,
      firstPrize: 100,
      secondPrize: 23,
      thirdPrize: 34,
    },
    description: "Top prize for last player standing",
    battleground: "Islands of Fury",
    teamSize: "Solo",
    maxTeams: 100,
    enrolled: 50,
    startingTime: "2025-03-05T18:00:00Z",
    thumbnailUrl: pubg,
    subtitle:
      "A battle royale for the toughest players, where only one can claim victory.",
    date: "2025-03-20T16:00:00.000Z",
    entryFee: 200,
    regions: "North America",
    skillLevel: "Advanced",
    game: "pubg",
    platform: "pc",
    enrolledTeams: 80,
    enrollmentStatus: true,
    registrationStatus: true,
  },
];
